apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: emerald-pg-app
  namespace: pokemonemeraldonline3ds
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: emerald-pg-app
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: kubernetes.io/basic-auth
      data:
        username: emerald
        password: '{{ .database_password }}'
  data:
    - secretKey: database_password
      remoteRef:
        key: lws/runtime/emerald-online-3ds
        property: database_password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: emerald-runtime
  namespace: pokemonemeraldonline3ds
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: emerald-runtime
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      data:
        PGHOST: emerald-pg-rw.pokemonemeraldonline3ds.svc.cluster.local
        PGPORT: "5432"
        PGDATABASE: emerald
        PGUSER: emerald
        PGPASSWORD: '{{ .database_password }}'
        IDENTITY_PEPPER: '{{ .identity_pepper }}'
  data:
    - secretKey: database_password
      remoteRef:
        key: lws/runtime/emerald-online-3ds
        property: database_password
    - secretKey: identity_pepper
      remoteRef:
        key: lws/runtime/emerald-online-3ds
        property: identity_pepper
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: emerald-backup
  namespace: pokemonemeraldonline3ds
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: emerald-backup
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: ACCESS_KEY_ID
      remoteRef:
        key: lws/runtime/emerald-online-3ds
        property: backup_access_key
    - secretKey: ACCESS_SECRET_KEY
      remoteRef:
        key: lws/runtime/emerald-online-3ds
        property: backup_secret_key
