#ifndef EMERALD_ONLINE_LOCALIZATION_H
#define EMERALD_ONLINE_LOCALIZATION_H

#include <3ds.h>

enum LocalizedString {
    // Bottom-screen page titles.
    LS_EMERALD_ONLINE,
    LS_ONLINE_USERS_READ_ONLY,
    LS_CHAT,
    LS_PARTY_LOCAL_ONLY,
    LS_BAG_LOCAL_ONLY,
    LS_MAP_TRAINER_RADAR,
    LS_PLAYER_STATS_AND_CONSENT,
    LS_TELEPORT,
    LS_SYSTEM_UPDATE,

    // Header / navigation.
    LS_Y_ARROW,

    // Party page.
    LS_WAITING_EMERALD_MEMORY_PARTY,
    LS_Y_BAG,
    LS_LEVEL_FORMAT,

    // Online status labels.
    LS_ONLINE,
    LS_CONNECTING,
    LS_RETRYING,
    LS_OFFLINE,

    // Profile overview.
    LS_ID_FORMAT,
    LS_FPS_FORMAT,
    LS_MAP_TILE_FORMAT,
    LS_WAITING_OVERWORLD,
    LS_RECOVERY_WRITE_DOWN_FORMAT,
    LS_VERSION_HOST_PORT_FORMAT,
    LS_TAP_PROFILE_PAIR_BROWSER,

    // Network diagnostic overlay.
    LS_NETWORK_DIAGNOSTIC,
    LS_NETWORK_DIAGNOSTIC_DETAIL_FORMAT,
    LS_TLS_RESULT_FORMAT,
    LS_VERIFY_CLOCK_FORMAT,
    LS_LOG_PATH_LABEL,

    // Online overview panels.
    LS_NEARBY_ONLINE_FORMAT,
    LS_TAP_FOR_ALL_USERS,
    LS_TAP_FOR_MESSAGES,

    // Emote / action buttons.
    LS_WAVE,
    LS_BATTLE,
    LS_TRADE,
    LS_GG,
    LS_HI,
    LS_EXCLAMATION,
    LS_ANGLED_BRACKETS,

    // ROM load failure.
    LS_COULD_NOT_LOAD_EMERALD_GBA,
    LS_3DS_EMERALD_ONLINE_3DS,

    // Bag page.
    LS_WAITING_VALID_EMERALD_MEMORY,
    LS_LOCAL_ONLY_MONEY_FORMAT,
    LS_POCKET_IS_EMPTY,
    LS_PREVIOUS,
    LS_NEXT,
    LS_POCKET_ITEMS,
    LS_POCKET_KEY,
    LS_POCKET_BALLS,
    LS_POCKET_TM_HM,
    LS_POCKET_BERRY,
    LS_UNKNOWN_ITEM,

    // Map page.
    LS_WAITING_EMERALD_OVERWORLD,
    LS_PLAYER_MARKER,
    LS_LOCAL_RADAR,
    LS_MAP_FORMAT,
    LS_TILE_FORMAT,
    LS_FACING_FORMAT,
    LS_NEARBY_FORMAT,
    LS_NO_TRAINERS,

    // Stats page.
    LS_PRIVATE_BY_DEFAULT,
    LS_LOCAL_SEEN_CAUGHT_BADGES_FORMAT,
    LS_POKEDEX_SEEN,
    LS_POKEDEX_CAUGHT,
    LS_BADGE_COUNT,
    LS_FRONTIER_STREAKS,
    LS_ON,
    LS_OFF,
    LS_UPLOADS_OFF_TAP_ENABLE,
    LS_ENABLE_UPLOAD_EXPLICIT_CONSENT,
    LS_SYNC_NOW,
    LS_DELETE_ALL_STATS,
    LS_SYNC_SENT_COMMUNITY_SUBMITTED,
    LS_CONSENT_SAVED_ON_SERVER,
    LS_COULD_NOT_SAVE_STATS_CFG,
    LS_NOT_ENABLED_NO_DATA_UPLOADED,
    LS_CONSENT_SAVED_SYNCING,
    LS_FIELD_ENABLED_SYNCING,
    LS_FIELD_DISABLED_SERVER_DATA_REMOVED,
    LS_DELETE_CANCELLED,
    LS_DELETE_SENT_UPLOADS_OFF,
    LS_CONNECT_ONLINE_TO_SYNC,
    LS_WAITING_FOR_VALID_SAVE_MEMORY,
    LS_SCORES_SYNCED,
    LS_SENT_VALUES_UNDER_REVIEW,

    // Users page.
    LS_GLOBAL_MAP_TILE_POSITIONS_FORMAT,
    LS_TRAINER,
    LS_TYPE,
    LS_MAP_TILE,
    LS_WAITING,
    LS_WAITING_ONLINE_ROSTER,
    LS_CONNECT_ONLINE_VIEW_USERS,

    // Chat page.
    LS_MAP_CHAT,
    LS_GLOBAL_CHAT,
    LS_GLOBAL_MSG_SESSION_UTC_TAP_FORMAT,
    LS_MSG_MAP_UTC_TAP_FORMAT,
    LS_CURRENT_MAP_SESSION_UTC,
    LS_BACK,
    LS_NO_GLOBAL_MESSAGES_SESSION,
    LS_NO_MESSAGES_MAP,
    LS_WAITING_OVERWORLD_CHAT,
    LS_COMPOSE,

    // Teleport page.
    LS_TELEPORT_ALL,
    LS_TELEPORT_GYMS,
    LS_TELEPORT_LOCS,
    LS_TELEPORT_PLAYERS,
    LS_TELEPORT_MOM,
    LS_TELEPORT_CUSTOM,
    LS_WAITING_DESTINATIONS,
    LS_CONNECT_ONLINE_TELEPORT,
    LS_TELEPORT_BUTTON,
    LS_ADD_CUSTOM,
    LS_INVALID_FORMAT_USE_MAP_MAP_X_Y,
    LS_COORDINATES_OUT_OF_RANGE,
    LS_CUSTOM_DEST_SENT_FOR_APPROVAL,
    LS_FAILED_TO_SEND_CUSTOM_DEST,
    LS_WARP_FAILED_FORMAT,
    LS_WARP_FAILED_BAD_COORDS,
    LS_WARPED_TO_FORMAT,

    // Update page.
    LS_CURRENT_VERSION_FORMAT,
    LS_LATEST_VERSION_FORMAT,
    LS_KB_FORMAT,
    LS_CHECK_FOR_UPDATE,
    LS_DOWNLOAD,
    LS_INSTALL,
    LS_EXIT_RELAUNCH,
    LS_CHECKING_FOR_UPDATE,
    LS_UPDATE_CHECK_FAILED,
    LS_UPDATE_RESPONSE_INVALID,
    LS_UP_TO_DATE_FORMAT,
    LS_UPDATE_AVAILABLE_FORMAT,
    LS_DOWNLOADING,
    LS_DOWNLOAD_FAILED,
    LS_VERIFYING,
    LS_HASH_MISMATCH,
    LS_READY_TAP_INSTALL,
    LS_INSTALLING,
    LS_INSTALL_FAILED,
    LS_DONE_EXIT_RELAUNCH,

    // Link status strings.
    LS_LINK_SPIKE_DISABLED,
    LS_LINK_RECONNECTING,
    LS_JOIN_SENT,
    LS_LINK_WAITING_FORMAT,
    LS_LINK_ACTIVE_BACKUP_OK_FORMAT,
    LS_LINK_BLOCKED_SAVE_BACKUP_FAILED,
    LS_LINK_BLOCKED_BY_CORE,
    LS_LINK_PEER_DISCONNECTED,
    LS_LINK_SESSION_ENDED,
    LS_LINK_STATUS_TX_RX_FORMAT,
    LS_SERVER_FORMAT,

    // Browser pairing strings.
    LS_BROWSER_PAIRED,
    LS_PAIRING_CODE_EXPIRED,
    LS_INVALID_PAIRING_CODE,
    LS_PAIRING_APPROVAL_SENT,
    LS_PAIRING_SEND_FAILED,

    // System keyboard hints.
    LS_HINT_CUSTOM_DESTINATION_NAME,
    LS_HINT_MAPGROUP_MAPNUM_X_Y,
    LS_HINT_BROWSER_CODE,
    LS_HINT_TYPE_YES_UPLOAD,
    LS_HINT_TYPE_DELETE_ERASE,

    // Quest / NPC strings.
    LS_QUEST_LOG,
    LS_NO_QUESTS,
    LS_TALK,
    LS_HARVEST,
    LS_ACCEPT_QUEST,
    LS_QUEST_COMPLETED,
    LS_QUEST_REWARD_TITLE,
    LS_NPC_DIALOGUE_TITLE,
    LS_QUEST_ACCEPTED,

    // Title / friend strings.
    LS_TITLE_LOG,
    LS_FRIENDS_LIST,
    LS_NO_TITLES,
    LS_NO_FRIENDS,
    LS_EQUIPPED,

    // Guild strings.
    LS_GUILD,
    LS_NO_GUILD,

    LS_COUNT
};

enum class Language {
    English,
    // Future languages append here.
};

bool localizationInit(void);
void localizationShutdown(void);
const char* localize(LocalizedString key);
Language localizationCurrentLanguage(void);

#endif
