function escapeHtml(value) {
  return String(value)
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;')
    .replaceAll("'", '&#39;');
}

export function installPage({ version, publicBase, gamePublicUrl, ciaUrl, desktopInstallerPresent, desktopLinuxInstallerPresent, iosIpaPresent = false }) {
  const safeVersion = escapeHtml(version);
  const safePublicBase = escapeHtml(publicBase);
  const safeGamePublicUrl = escapeHtml(gamePublicUrl);
  const safeCiaUrl = escapeHtml(ciaUrl);
  const desktopHref = desktopInstallerPresent ? '/download/desktop' : '#';
  const desktopDisabled = desktopInstallerPresent ? '' : ' aria-disabled="true"';
  const desktopLabel = desktopInstallerPresent ? 'Download Windows installer' : 'Windows installer coming soon';
  const linuxHref = desktopLinuxInstallerPresent ? '/download/desktop-linux' : '#';
  const linuxDisabled = desktopLinuxInstallerPresent ? '' : ' aria-disabled="true"';
  const linuxLabel = desktopLinuxInstallerPresent ? 'Download Linux desktop' : 'Linux app coming soon';
  const sideStoreSourceUrl = `${publicBase}/sidecommunity.json`;
  const sideStoreDeepLink = `sidestore://source?url=${encodeURIComponent(sideStoreSourceUrl)}`;
  const iosDownload = iosIpaPresent
    ? '<a class="button secondary" href="/download/ios">Download signed IPA</a>'
    : '<span class="button secondary disabled" aria-disabled="true">Signed IPA coming soon</span>';
  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<link rel="icon" type="image/png" href="/favicon.png"><link rel="stylesheet" href="/site.css">
<meta name="description" content="Install Emerald Online 3DS, see verified Union Room trading, and check the public service status.">
<meta property="og:title" content="Emerald Online 3DS"><meta property="og:description" content="Play your own legally obtained Pokémon Emerald copy on Nintendo 3DS with online presence, chat, emotes, and community forums.">
<meta property="og:type" content="website"><meta property="og:url" content="${safePublicBase}/"><meta property="og:image" content="${safePublicBase}/logo.png">
<meta name="twitter:card" content="summary_large_image"><meta name="theme-color" content="#061b16"><title>Emerald Online 3DS</title></head>
<body><a class="skip-link" href="#main">Skip to content</a><header class="site-header"><a class="brand" href="/" aria-current="page"><img src="/logo.png" width="48" height="48" alt=""><span>Emerald Online 3DS<small>Public multiplayer beta · v${safeVersion}</small></span></a><nav aria-label="Primary"><a href="#install">Install</a><a href="/community">Community</a><a href="/status">Status</a></nav></header>
<main id="main"><section class="hero"><div class="hero-copy"><div class="eyebrow">Your Emerald adventure, connected</div><h1>Emerald <span>Online</span> 3DS</h1><p class="lede">Play your own legally obtained Emerald copy while seeing trainers on the same map, chatting, sharing emotes, and using the community—without creating an account.</p><div class="hero-actions"><a class="button" href="#install">Choose an install</a><a class="button secondary" href="/community">Explore the community</a></div><div class="status" role="status" aria-live="polite"><span class="dot" aria-hidden="true"></span><span id="status">Checking multiplayer…</span><span class="status-sep" aria-hidden="true">·</span><span id="health" class="health-badge">Checking services…</span></div></div><figure class="hero-preview"><img src="/release-media/0.8.8-map-global-chat.png" width="900" height="720" alt="Emerald Online 3DS lower-screen Map Chat and Global Chat interface"><figcaption>Map and global chat on the 3DS lower screen</figcaption></figure></section>
<section class="install-card" id="install"><div class="section-heading"><div><div class="eyebrow">Get started</div><h2>Choose where you want to play</h2><p>Your ROM and save stay private on your device. Pairing the community is optional and never requires registration.</p></div></div>
<div class="install-tabs" role="tablist" aria-label="Installation method"><button id="tab-windows" role="tab" aria-selected="true" aria-controls="panel-windows" data-install-tab="windows">Windows</button><button id="tab-linux" role="tab" aria-selected="false" aria-controls="panel-linux" data-install-tab="linux">Linux</button><button id="tab-ios" role="tab" aria-selected="false" aria-controls="panel-ios" data-install-tab="ios">iPhone / iPad</button><button id="tab-cia" role="tab" aria-selected="false" aria-controls="panel-cia" data-install-tab="cia">Nintendo 3DS</button><button id="tab-3dsx" role="tab" aria-selected="false" aria-controls="panel-3dsx" data-install-tab="3dsx">3DSX</button></div>
<div id="panel-windows" class="install-panel" role="tabpanel" aria-labelledby="tab-windows" data-install-panel="windows"><div><h3>Windows guided installer</h3><p>Use the desktop helper to validate your private Emerald dump and prepare the SD-card folder without uploading game data.</p><a class="button${desktopInstallerPresent ? '' : ' disabled'}" href="${desktopHref}"${desktopDisabled}>${desktopLabel}</a></div><div class="privacy-note"><strong>Private by design</strong><span>The installer works locally. ROMs, saves, identity files, and recovery codes are never sent to this website.</span></div></div>
<div id="panel-linux" class="install-panel" role="tabpanel" aria-labelledby="tab-linux" data-install-panel="linux" hidden><div><h3>Linux desktop</h3><p>Use the desktop helper package for the same private ROM-first workflow in Linux environments.</p><a class="button${desktopLinuxInstallerPresent ? '' : ' disabled'}" href="${linuxHref}"${linuxDisabled}>${linuxLabel}</a></div></div>
<div id="panel-ios" class="install-panel" role="tabpanel" aria-labelledby="tab-ios" data-install-panel="ios" hidden><div><h3>Install with SideStore</h3><p>Add the official JSON source, install the dedicated app, then select your own supported cartridge dump inside the launcher. The IPA contains no ROM or save and cannot browse or launch other games.</p><div class="actions"><a class="button" href="${escapeHtml(sideStoreDeepLink)}">Add to SideStore</a>${iosDownload}</div><code class="download-url">${escapeHtml(sideStoreSourceUrl)}</code></div><div class="privacy-note"><strong>Private app sandbox</strong><span>Your imported ROM, save, identity, settings, and backups stay inside the app unless you explicitly export them.</span></div></div>
<div id="panel-cia" class="install-panel" role="tabpanel" aria-labelledby="tab-cia" data-install-panel="cia" hidden><div class="install-copy"><h3>Install the CIA with FBI</h3><ol><li>Back up and prepare <code>sd:/3ds/emerald-online-3ds/</code>.</li><li>Open FBI, choose <b>Remote Install</b>, then <b>Scan QR Code</b>.</li><li>Scan this code and launch Emerald Online 3DS.</li></ol><div class="actions"><a class="button" href="/emerald-online-3ds.cia">Download CIA</a><button class="button secondary" id="copy-cia" type="button">Copy CIA URL</button></div><code id="cia-url" class="download-url">${safeCiaUrl}</code></div><details class="qr-card"><summary>Show FBI QR code</summary><div class="qr"><img src="/qr.svg" width="360" height="360" alt="QR code for the Emerald Online 3DS CIA download"></div></details></div>
<div id="panel-3dsx" class="install-panel" role="tabpanel" aria-labelledby="tab-3dsx" data-install-panel="3dsx" hidden><div><h3>Homebrew Launcher</h3><p>Copy the 3DSX and your private files into the application folder, then launch it through Homebrew Launcher.</p><pre>sd:/3ds/emerald-online-3ds/<br>  emerald.gba<br>  online.cfg<br>  emerald-online-3ds.3dsx</pre><a class="button" href="/emerald-online-3ds.3dsx">Download 3DSX</a></div></div>
<p class="artifact-links"><a href="/source">3DS runtime source</a><a href="/SHA256SUMS">Verify downloads</a><a href="/community?guide=install-on-3ds">Full installation guide</a></p></section>
<section class="showcase" id="prepare"><div class="eyebrow">Required before launch</div><h2>Prepare your private files</h2><div class="info-grid"><div><h3>Supported cartridge dump</h3><p>The runtime supports the unmodified Pokémon Emerald US cartridge revision with game code <code>BPEE</code>, revision 0, and SHA-256 <code>a9dec84dfe7f62ab2220bafaef7479da0929d066ece16a6885f6226db19085af</code>. Validate it locally; never upload it.</p><p>Back up the complete folder before updating. Preserve <code>emerald.sav</code>, <code>identity.cfg</code>, <code>stats.cfg</code>, <code>avatars.t3x</code>, and <code>link-backups/</code>.</p></div><div><h3>Public configuration</h3><pre>server=live.emeraldonline3ds.com<br>port=443<br>transport=wss<br>path=/game<br>name=Trainer</pre><p>Never put credentials or recovery codes in <code>online.cfg</code>. The app creates its anonymous identity separately on first connection.</p></div></div></section>
<section class="showcase"><div class="eyebrow">What works today</div><h2>A multiplayer layer built around Emerald</h2><div class="feature-grid"><article><h3>Nearby trainers</h3><p>See authenticated trainers sharing your map while the original game remains locally simulated.</p></article><article><h3>Map and global chat</h3><p>Switch between nearby conversation and a session-only global channel.</p></article><article><h3>Native link experiment</h3><p>A complete two-Azahar Union Room trade passes. Physical 3DS trading, battles, interruption recovery, audio, and performance remain acceptance work.</p></article></div></section>
<section class="showcase"><div class="eyebrow">Privacy at a glance</div><h2>Your game stays yours</h2><div class="info-grid"><div><h3>Online presence</h3><p>The service receives an anonymous device identity, display name, and current presence state. Gameplay snapshots and emotes stay map-local. Map and Global Chat are relayed without server storage.</p></div><div><h3>Never uploaded</h3><p>The service never receives your ROM, save, Trainer ID, Pokémon, moves, party, or inventory. Save-derived leaderboard fields remain off until you explicitly enable them.</p><p><a href="/community?guide=privacy-and-data">Read the privacy and data-control guide</a>.</p></div></div></section>
<section class="showcase"><div class="eyebrow">Authentic project captures</div><h2>See the experience</h2><div class="shots"><figure><img src="/release-media/0.8.7-trading-board.png" alt="Native Union Room Trading Board offer through the public relay" loading="lazy"><figcaption>Two isolated Azahar clients discovered the same native Trading Board offer.</figcaption></figure><figure><img src="/release-media/0.8.7-union-room-trade.png" alt="Native Pokémon Emerald Union Room trade animation" loading="lazy"><figcaption>The acceptance run completed the animation, automatic save, restart, and party exchange.</figcaption></figure><figure><img src="/release-media/community-forums.png" alt="Emerald Online 3DS community forum" loading="lazy"><figcaption>Public releases, installation guides, service status, defects, and paired-player boards.</figcaption></figure><figure><img src="/release-media/0.8.4-online-users.png" alt="Read-only global Online Users list on the 3DS lower screen" loading="lazy"><figcaption>The global roster shows online trainers without exposing private game or save data.</figcaption></figure></div></section>
<section class="endpoint-strip"><div><div class="eyebrow">Public game endpoint</div><code>${safeGamePublicUrl}</code></div><a class="button secondary" href="/status">View live status</a></section>
<footer class="site-footer"><h2>Independent community project</h2><p>Emerald Online 3DS is an unofficial, fan-made homebrew beta. It is not affiliated with, endorsed by, or sponsored by Nintendo, The Pokémon Company, or Game Freak.</p><p class="legal">This project does not host, sell, or distribute ROMs, game files, encryption keys, copyrighted artwork, or copyrighted audio. Back up your save before testing and never share <code>identity.cfg</code> or a recovery code.</p><nav aria-label="Project links"><a href="#install">Install</a><a href="/community">Community &amp; defects</a><a href="/community?guide=privacy-and-data">Privacy &amp; data controls</a><a href="/status">Live status</a><a href="/source">Runtime source</a><a href="/SHA256SUMS">Verify downloads</a></nav></footer></main><script src="/install-page.js" defer></script></body></html>`;
}
