export function statusPage(version) {
  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<link rel="icon" type="image/png" href="/favicon.png"><meta name="description" content="Live Emerald Online 3DS public service status and URLs.">
<title>Service Status · Emerald Online 3DS</title><style>
:root{color-scheme:dark;font-family:ui-rounded,system-ui,sans-serif;background:#061b16;color:#effff8}*{box-sizing:border-box}body{margin:0;min-height:100vh;background:radial-gradient(circle at 12% 0,#176348,#061b16 54%);padding:28px 16px}main{width:min(940px,100%);margin:auto}.top{display:flex;justify-content:space-between;align-items:center;gap:18px;margin-bottom:22px}.brand{display:flex;align-items:center;gap:12px;color:#effff8;text-decoration:none;font-weight:900}.brand img{width:54px;border-radius:22%}.button{padding:11px 15px;border-radius:10px;background:#58d69a;color:#052017;text-decoration:none;font-weight:900}.panel{background:#09251fee;border:1px solid #65d6a244;border-radius:20px;padding:26px;box-shadow:0 18px 60px #0005}.eyebrow{color:#74dfad;font-weight:900;letter-spacing:.1em;text-transform:uppercase;font-size:.78rem}h1{margin:.35rem 0;font-size:clamp(2rem,6vw,3.8rem)}.summary{color:#b8ddcc;margin-bottom:24px}.services{display:grid;gap:12px}.service{display:grid;grid-template-columns:auto minmax(0,1fr) auto;gap:14px;align-items:center;padding:16px;border:1px solid #4e9f7a66;border-radius:14px;background:#061b16}.light{width:15px;height:15px;border-radius:50%;background:#82938b;box-shadow:0 0 14px #82938b}.service.operational .light{background:#53e394;box-shadow:0 0 15px #53e394}.service.outage .light{background:#ff646f;box-shadow:0 0 15px #ff646f}.name{font-weight:900}.url{display:block;color:#7ce6b4;word-break:break-all;font:0.84rem ui-monospace,monospace;margin-top:4px}.state{font-weight:900}.service.operational .state{color:#72edaa}.service.outage .state{color:#ff8a92}.note{margin-top:22px;color:#a8cfbd;line-height:1.55}.checked{color:#8fb8a6;font-size:.86rem}@media(max-width:680px){.service{grid-template-columns:auto minmax(0,1fr)}.state{grid-column:2}.top{align-items:flex-start}.panel{padding:19px}}
</style></head><body><main><header class="top"><a class="brand" href="/"><img src="/logo.png" alt=""><span>Emerald Online 3DS<br><small>v${version}</small></span></a><a class="button" href="/community?category=service-status">Status forum</a></header>
<section class="panel"><div class="eyebrow">Live public checks</div><h1>Service status</h1><p id="summary" class="summary">Checking public services…</p><div id="services" class="services"></div><p id="checked" class="checked"></p><p class="note">Green means the server-side check passed. Red means that path is currently unavailable. A green service check does not prove physical 3DS compatibility; console behavior still requires the hardware checklist. No private cluster, database, or host address is published here.</p></section></main><script>
const host=document.getElementById('services'),summary=document.getElementById('summary'),checked=document.getElementById('checked');
function draw(data){host.replaceChildren();for(const item of data.services){const row=document.createElement('article');row.className='service '+item.status;const light=document.createElement('span');light.className='light';light.setAttribute('aria-hidden','true');const copy=document.createElement('div'),name=document.createElement('div'),url=document.createElement('a'),state=document.createElement('div');name.className='name';name.textContent=item.name;url.className='url';url.href=item.url;url.textContent=item.url;url.rel='noreferrer noopener';state.className='state';state.textContent=item.status==='operational'?'Operational':'Outage';copy.append(name,url);row.append(light,copy,state);host.append(row)}summary.textContent=data.ok?'All monitored public services are operational.':'One or more monitored services are unavailable.';checked.textContent='Last checked '+new Date(data.checkedAt).toLocaleString();}
fetch('/api/public-status',{cache:'no-store'}).then(async response=>{const data=await response.json();draw(data)}).catch(()=>draw({ok:false,checkedAt:new Date().toISOString(),services:[{name:'Status API',url:location.origin+'/api/public-status',status:'outage'}]}));
</script></body></html>`;
}
